//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlineSatranc.Models.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class kullanicilar
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public kullanicilar()
        {
            this.arkadasliklar = new HashSet<arkadasliklar>();
            this.arkadasliklar1 = new HashSet<arkadasliklar>();
            this.satrancTahtalari = new HashSet<satrancTahtalari>();
            this.satrancTahtalari1 = new HashSet<satrancTahtalari>();
        }
    
        public int ID { get; set; }
        public string Ad { get; set; }
        public string Soyad { get; set; }
        public string ePosta { get; set; }
        public string gsm { get; set; }
        public string kAdi { get; set; }
        public string sifre { get; set; }
        public int ELO { get; set; }
        public Nullable<System.DateTime> dgmTarihi { get; set; }
        public bool cinsiyet { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<arkadasliklar> arkadasliklar { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<arkadasliklar> arkadasliklar1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<satrancTahtalari> satrancTahtalari { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<satrancTahtalari> satrancTahtalari1 { get; set; }
    }
}
