//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlineSatranc.Models.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class satrancTahtalari
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public satrancTahtalari()
        {
            this.hamleler = new HashSet<hamleler>();
        }
    
        public int ID { get; set; }
        public int odaSahibi { get; set; }
        public Nullable<int> rakip { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<hamleler> hamleler { get; set; }
        public virtual kullanicilar kullanicilar { get; set; }
        public virtual kullanicilar kullanicilar1 { get; set; }
    }
}
